#!/bin/bash
# By Robert J. Gebis (oxoocoffee)
# rjgebis AT g mail DOT com

echo ""
echo "+++ Required ROS Environment Variables ++++++"
echo "ROS_WORKSPACE:                  $ROS_WORKSPACE"
echo "ROS_DISTRO:                     $ROS_DISTRO"
echo "ROS_ROOT:                       $ROS_ROOT"
echo "ROS_MASTER_URI:                 $ROS_MASTER_URI"
echo "ROS_LOCATIONS:                  $ROS_LOCATIONS"
echo "PYTHONPATH:                     $PYTHONPATH"
echo ""
echo "+++ Additional PATH Environment Variables +++"
echo "ROS_PACKAGE_PATH:               $ROS_PACKAGE_PATH"
echo ""
echo "+++ System Data Environment Variables +++++++"
echo "ROS_HOME:                       $ROS_HOME"
echo "ROS_LOG_DIR:                    $ROS_LOG_DIR"
echo "ROS_TEST_RESULTS_DIR:           $ROS_TEST_RESULTS_DIR"
echo "ROSLISP_PACKAGE_DIRECTORIES:    $ROSLISP_PACKAGE_DIRECTORIES"
echo ""
echo "+++ Node Environment Variables ++++++++++++++"
echo "ROS_HOSTNAME:                   $ROS_HOSTNAME"
echo "ROS_IP:                         $ROS_IP"
echo "ROS_NAMESPACE:                  $ROS_NAMESPACE"
echo "ROSCONSOLE_CONFIG_FILE:         $ROSCONSOLE_CONFIG_FILE"
echo "ROSCONSOLE_FORMAT:              $ROSCONSOLE_FORMAT"
echo "ROS_PYTHON_LOG_CONFIG_FILE:     $ROS_PYTHON_LOG_CONFIG_FILE"
echo ""
echo "+++ Build System Environment Variables ++++++"
echo "ROS_BOOST_ROOT:                 $ROS_BOOST_ROOT"
echo "ROS_PARALLEL_JOBS:              $ROS_PARALLEL_JOBS"
echo "ROS_LANG_DISABLE:               $ROS_LANG_DISABLE"
echo "ROS_OS_OVERRIDE:                $ROS_OS_OVERRIDE"
echo ""
echo "+++ System Environment Variables ++++++++++++"
echo "PATH:                           $PATH"
echo "LD_LIBRARY_PATH:                $LD_LIBRARY_PATH"
echo "CMAKE_PREFIX_PATH:              $CMAKE_PREFIX_PATH"
echo "CPATH:                          $CPATH"
echo ""
echo ""
