#!/bin/bash
# By Robert J. Gebis (oxoocoffee)
# rjgebis AT g mail DOT com

unset LD_LIBRARY_PATH 
unset PKG_CONFIG_PATH
unset ROS_DISTRO
unset ROS_ROOT
unset ROS_MASTER_URI
unset PYTHONPATH
unset ROS_PACKAGE_PATH
unset ROS_HOME
unset ROS_LOG_DIR
unset ROS_TEST_RESULTS_DIR
unset ROSLISP_PACKAGE_DIRECTORIES
unset ROS_LOCATIONS
unset ROS_WORKSPACE
unset ROS_HOSTNAME
unset ROS_IP
unset ROS_NAMESPACE
unset ROSCONSOLE_CONFIG_FILE
unset ROSCONSOLE_FORMAT
unset ROS_PYTHON_LOG_CONFIG_FILE
unset ROS_BOOST_ROOT
unset ROS_PARALLEL_JOBS
unset ROS_LANG_DISABLE
unset ROS_OS_OVERRIDE
unset ROS_ETC_DIR
unset CATKIN_TEST_RESULTS_DIR
